### ISSUE TITLE
make index!

### ISSUE THREAD

**Issue by tbrown122387** [tbrown122387/r_and_python_book#13]
make index!

**Comment by tbrown122387** [comment]
- [x]  integrated development environments environments (IDEs)
- [x]  console
- [x]  script

- [x]  assignment operator (in R, in Python)
- [x]  working directory 
- [x]  escape character
- [x]  type
- [x]  type conversion
- [x]  classes
- [x]  vectors
- [x]  array (in R, Numpy in Python, see also ndarray)
- [x]  vectorization (see also broadcasting)
- [x]  broadcasting
- [x]  universal functions
- [x]  Series
- [x]  indexing (see also slicing, in R, Python)
- [x]  slicing
- [x]  copies (deep, shallow, view)

- [x]  missing data
- [x]  regular expressions

- [x]  matrix
- [x]  lists (disambiguation)
- [x]  dicts
- [x]  functions
- [x]  first-class functions
- [x]  pure
- [x]  decorators
- [x]  calling

- [x]  environment (global)
- [x]  namespace
- [x]  scoping (lexical)
- [x]  closures
- [x]  LEGB
- [x]  pass-by-value
- [x]  pass-by-assignment
- [x]  mutable
- [x]  capturing
- [x]  dynamic lookup
- [x]  side effects
- [x]  factors
- [x]  Pandas
- [x]  ggplot
- [x]  matplotlib
- [x]  Data Frames (in R, in Python)
- [x]  Serialization (check this definition and cite it)
- [x]  pickling
- [x]  packages
- [x]  modules
- [x]  libraries
- [x]  search path
- [x]  if statement
- [x]  loop (for loop, while loop, both R and Python)
- [x]  merge/join
- [x]  plotting (disambiguation)
- [x]  matplotlib
- [x]  tuple
- [x]  object-oriented programming
- [x]  S3,S4,Referneces classes, R6 classes
- [x]  Composition
- [x]  Inheritance
- [x]  Polymorphism
- [x]  Encapsulation
- [x]  Modularity
- [x]  interface
- [x]  implementation (need citation)
- [x]  instances
- [x]  attributes (TODO how to get a "see also" data members)
- [x]  methods (disambiguation in R/Python)
- [x]  dunder (aka special aka magic) methods
- [x]  method dispatch
- [x]  DRY
- [x]  WET
- [x]  functional programming

**Comment by amifalk** [comment]
index for "Series"

**Comment by JulietteLaburthe** [comment]
index for "Pandas" , "ggplot" , "matplotlib" , "slicing" , and "dicts"
