### ISSUE TITLE
Zillow data is missing from data folder

### ISSUE THREAD

**Issue by amifalk** [tbrown122387/r_and_python_book#19]
Chapter 8 exercises, R question 3

**Comment by tbrown122387** [comment]
Note to myself: there should be some note in the preface where I mention that, even though all data sets are cited, the files are available for download

**Comment by tbrown122387** [comment]
I think these are all the files that need to be added:

`sim_data.csv`
`kr-vs-kp.data`
`Zip_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv`
`X_train.txt` 
`y_train.txt`
