### ISSUE TITLE
track down rights to data sets

### ISSUE THREAD

**Issue by tbrown122387** [tbrown122387/r_and_python_book#5]
Right now, all the data in [`/data`](https://github.com/tbrown122387/r_and_python_book/tree/master/data) needs to have rights tracked down and secured. Many of the small ones I created, but we also have

- [x]  `cars.csv` which I think is sashelp.cars
- [x]  `iris.csv` which is famous
- [x]  the Albemarle real estate one

**Comment by perveen-neha** [comment]
what do you mean by rights tracked down and secured, how do we do that . please let me know , I hope I can help you get the task done
